# Generated by Django 5.2.16 on 2026-08-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی'),
        ),
    ]
