# Generated by Django 5.2.17 on 2026-09-10 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='شماره حساب یا شماره کارت برای واریز وجه', max_length=30, verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='نام بانک'),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, help_text='کد اختصاصی معرفی کاربران', max_length=10, null=True, unique=True, verbose_name='کد معرف'),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to=settings.AUTH_USER_MODEL, verbose_name='معرفی شده توسط'),
        ),
    ]
