# Generated by Django 5.2.17 on 2026-09-10 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_bank_account_number_user_bank_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=0, default=0, help_text='موجودی به تومان', max_digits=15, verbose_name='موجودی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'واریز'), ('withdraw', 'برداشت'), ('purchase', 'خرید'), ('revenue_share', 'سهم فروش'), ('referral_bonus', 'پاداش معرف'), ('designer_payment', 'پرداخت طراح'), ('refund', 'بازگشت وجه')], max_length=30, verbose_name='نوع تراکنش')),
                ('amount', models.DecimalField(decimal_places=0, help_text='مثبت = واریز، منفی = برداشت', max_digits=15, verbose_name='مبلغ')),
                ('balance_after', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='موجودی بعد از تراکنش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('related_id', models.CharField(blank=True, help_text='مثلاً شناسه پرداخت یا آزمون', max_length=100, verbose_name='شناسه مرتبط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='accounts_tr_wallet__68c661_idx'), models.Index(fields=['transaction_type'], name='accounts_tr_transac_9f7758_idx')],
            },
        ),
    ]
