services:

  db:
    image: postgres:17
    container_name: postgres_db

    environment:
      POSTGRES_DB: learning_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_web
    user: "1000:1000"
    command: sleep infinity

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
