services:

  db:
    image: postgres:17
    container_name: postgres_db

    environment:
      POSTGRES_DB: learning_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # همیشه md5 (نه scram-sha-256)
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=trust"
      POSTGRES_PASSWORD_ENCRYPTION: md5

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      # اجرای init.sql موقع ساخت اولیه
      - ./docker/postgres-init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres && psql -U postgres -d postgres -c \"ALTER USER postgres WITH LOGIN SUPERUSER PASSWORD 'postgres';\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  web:
    build: .
    container_name: django_web
    user: "1000:1000"
    command: >
      bash -c "cd /app &&
               python manage.py migrate --noinput &&
               gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --no-control-socket"
    restart: unless-stopped

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
