# Generated by Django 5.2.16 on 2026-08-18 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0022_alter_questioncategory_options'),
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='conversation', to='education.instructorassignment', verbose_name='رابطه آموزشی')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_conversations', to=settings.AUTH_USER_MODEL, verbose_name='مدرس')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='assessments.learningpath', verbose_name='مسیر آموزشی')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_conversations', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'گفتگو',
                'verbose_name_plural': 'گفتگوها',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['instructor', 'student'], name='messaging_c_instruc_1374d1_idx'), models.Index(fields=['learning_path'], name='messaging_c_learnin_9890f8_idx'), models.Index(fields=['is_active'], name='messaging_c_is_acti_3f43be_idx')],
            },
        ),
    ]
