# Generated by Django 5.2.16 on 2026-08-18 14:29

import apps.messaging.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_conversationuserstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='messaging/', validators=[apps.messaging.validators.validate_message_file], verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, verbose_name='متن پیام'),
        ),
    ]
