# Generated by Django 5.2.16 on 2026-08-26 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message_file_alter_message_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='موضوع')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('file', models.FileField(blank=True, null=True, upload_to='direct_messages/', verbose_name='فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ خواندن')),
                ('is_archived_by_sender', models.BooleanField(default=False, verbose_name='بایگانی توسط فرستنده')),
                ('is_archived_by_receiver', models.BooleanField(default=False, verbose_name='بایگانی توسط گیرنده')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_direct_messages', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_direct_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'پیام مستقیم',
                'verbose_name_plural': 'پیام\u200cهای مستقیم',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'created_at'], name='messaging_d_sender__b97d8f_idx'), models.Index(fields=['receiver', 'created_at'], name='messaging_d_receive_4cca14_idx'), models.Index(fields=['read_at'], name='messaging_d_read_at_720fe1_idx')],
            },
        ),
    ]
