# Generated by Django 5.2.17 on 2026-09-03 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_directmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('open', 'باز'), ('in_progress', 'در حال بررسی'), ('closed', 'بسته')], default='open', max_length=20, verbose_name='وضعیت')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('normal', 'عادی'), ('high', 'زیاد')], default='normal', max_length=20, verbose_name='اولویت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='messaging_c_instruc_1374d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='messaging_c_learnin_9890f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='messaging_c_is_acti_3f43be_idx',
        ),
        migrations.RemoveIndex(
            model_name='directmessage',
            name='messaging_d_sender__b97d8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='directmessage',
            name='messaging_d_receive_4cca14_idx',
        ),
        migrations.RemoveIndex(
            model_name='directmessage',
            name='messaging_d_read_at_720fe1_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messaging_m_convers_7bc91b_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messaging_m_sender__259b0b_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messaging_m_read_at_f7d225_idx',
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
