from .learning_path import *
from .question import *
from .assessment import *
from .attempt import *
from .course_enrollment import *
from .course import *
from .scientific_group import *
from .course_instructor_assignment import *
from .payment import *
from .lesson import *
from .discount_code import *
