# Generated by Django 5.2.16 on 2026-08-02 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'واحدهای آموزشی', 'verbose_name_plural': 'واحدهای آموزشی'},
        ),
    ]
