# Generated by Django 5.2.16 on 2026-08-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_department'),
        ('assessments', '0031_remove_questioncategory_unique_category_name_per_parent_and_more'),
        ('core', '0002_alter_department_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
