# Generated by Django 5.2.16 on 2026-07-30 05:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True, help_text='در صورت نیاز، توضیح اختصاصی برای این گزینه')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'گزینه',
                'verbose_name_plural': 'گزینه\u200cهای سؤال',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('assessment_type', models.CharField(choices=[('level', 'تعیین سطح'), ('practice', 'تمرین'), ('homework', 'تکلیف'), ('final', 'پایان دوره'), ('retry', 'آزمون مجدد')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('passing_score', models.PositiveSmallIntegerField(default=70, help_text='حداقل درصد قبولی')),
                ('max_attempts', models.PositiveSmallIntegerField(default=1)),
                ('shuffle_questions', models.BooleanField(default=True)),
                ('shuffle_choices', models.BooleanField(default=True)),
                ('show_result_immediately', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'آزمون',
                'verbose_name_plural': 'آزمون\u200cها',
                'ordering': ['assessment_type', 'title'],
                'indexes': [models.Index(fields=['assessment_type'], name='assessments_assessm_f90c0d_idx'), models.Index(fields=['is_active'], name='assessments_is_acti_bdcae1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('current_question', models.PositiveSmallIntegerField(default=1)),
                ('total_questions', models.PositiveSmallIntegerField(default=0)),
                ('correct_answers', models.PositiveSmallIntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('passed', models.BooleanField(default=False)),
                ('elapsed_seconds', models.PositiveIntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='assessments.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تلاش آزمون',
                'verbose_name_plural': 'تلاش\u200cهای آزمون',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('not_visited', 'بازدید نشده'), ('visited', 'بازدید شده'), ('answered', 'پاسخ داده شده'), ('skipped', 'رد شده')], default='not_visited', max_length=20)),
                ('marked_for_review', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.attempt')),
            ],
            options={
                'verbose_name': 'سؤال آزمون',
                'verbose_name_plural': 'سؤال\u200cهای آزمون',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='AttemptChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True)),
                ('selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assessments.attemptquestion')),
                ('original_choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_snapshots', to='assessments.choice')),
            ],
            options={
                'verbose_name': 'گزینه آزمون',
                'verbose_name_plural': 'گزینه\u200cهای آزمون',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('weight', models.PositiveSmallIntegerField(default=1, help_text='اهمیت این هدف آموزشی در تحلیل یادگیری')),
                ('bloom_level', models.CharField(choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], default='understand', max_length=20)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=15, help_text='زمان تقریبی یادگیری این مبحث')),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisites', models.ManyToManyField(blank=True, to='assessments.learningobjective')),
            ],
            options={
                'verbose_name': 'هدف آموزشی',
                'verbose_name_plural': 'اهداف آموزشی',
                'ordering': ['category', 'order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'چهار گزینه\u200cای'), ('tf', 'صحیح / غلط'), ('msq', 'چند گزینه\u200cای'), ('short', 'پاسخ کوتاه'), ('code', 'کدنویسی')], default='mcq', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت')], default='medium', max_length=10)),
                ('score', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('estimated_seconds', models.PositiveSmallIntegerField(default=60, help_text='زمان تقریبی پاسخ (ثانیه)')),
                ('correct_answers_required', models.PositiveSmallIntegerField(default=1)),
                ('explanation', models.TextField(blank=True, help_text='توضیحی که بعد از پاسخ صحیح نمایش داده می\u200cشود.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_objective', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='assessments.learningobjective')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'بانک سؤالات',
                'ordering': ['learning_objective', 'code'],
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assessments.question'),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_questions', to='assessments.question'),
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='assessments.questioncategory')),
            ],
            options={
                'verbose_name': 'دسته سوال',
                'verbose_name_plural': 'دسته\u200cبندی سوالات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='learningobjective',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_objectives', to='assessments.questioncategory'),
        ),
        migrations.CreateModel(
            name='AssessmentRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت')], max_length=20, null=True)),
                ('question_count', models.PositiveSmallIntegerField(default=1)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='assessments.assessment')),
                ('learning_objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_rules', to='assessments.learningobjective')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_rules', to='assessments.questioncategory')),
            ],
            options={
                'verbose_name': 'قانون انتخاب سؤال',
                'verbose_name_plural': 'قوانین انتخاب سؤال',
                'ordering': ['assessment', 'category', 'learning_objective'],
            },
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['student'], name='assessments_student_f70c04_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['assessment'], name='assessments_assessm_6ac287_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['status'], name='assessments_status_cbd381_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptchoice',
            index=models.Index(fields=['attempt_question'], name='assessments_attempt_23a798_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptchoice',
            index=models.Index(fields=['selected'], name='assessments_selecte_9a6b6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='attemptchoice',
            constraint=models.UniqueConstraint(fields=('attempt_question', 'order'), name='unique_attempt_choice_order'),
        ),
        migrations.AddConstraint(
            model_name='attemptchoice',
            constraint=models.UniqueConstraint(fields=('attempt_question', 'original_choice'), name='unique_attempt_original_choice'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['learning_objective'], name='assessments_learnin_a70187_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='assessments_difficu_f7cef9_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active'], name='assessments_is_acti_d58c22_idx'),
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['question'], name='assessments_questio_c772aa_idx'),
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['is_correct'], name='assessments_is_corr_22fd58_idx'),
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='unique_choice_order_per_question'),
        ),
        migrations.AddIndex(
            model_name='attemptquestion',
            index=models.Index(fields=['attempt', 'order'], name='assessments_attempt_224cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptquestion',
            index=models.Index(fields=['status'], name='assessments_status_3268b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='attemptquestion',
            constraint=models.UniqueConstraint(fields=('attempt', 'order'), name='unique_attempt_question_order'),
        ),
        migrations.AddConstraint(
            model_name='attemptquestion',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_question'),
        ),
        migrations.AddIndex(
            model_name='questioncategory',
            index=models.Index(fields=['parent'], name='assessments_parent__bd306b_idx'),
        ),
        migrations.AddIndex(
            model_name='questioncategory',
            index=models.Index(fields=['is_active'], name='assessments_is_acti_abb9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='questioncategory',
            index=models.Index(fields=['order'], name='assessments_order_9c0950_idx'),
        ),
        migrations.AddConstraint(
            model_name='questioncategory',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_category_name_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='assessmentrule',
            constraint=models.UniqueConstraint(fields=('assessment', 'category', 'learning_objective', 'difficulty'), name='unique_assessment_rule'),
        ),
    ]
