# Generated by Django 5.2.16 on 2026-07-31 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questioncategory',
            name='unique_category_name_per_parent',
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_categories', to='core.department', verbose_name='دپارتمان'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='assessments.questioncategory'),
        ),
        migrations.AddConstraint(
            model_name='questioncategory',
            constraint=models.UniqueConstraint(fields=('department', 'parent', 'name'), name='unique_category_name_per_parent'),
        ),
    ]
