# Generated by Django 5.2.16 on 2026-08-02 18:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_remove_questioncategory_unique_category_name_per_parent_and_more'),
        ('core', '0002_alter_department_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='core.department'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='passing_score',
            field=models.PositiveSmallIntegerField(default=70, help_text='حداقل درصد قبولی', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='assessmentrule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_rules', to='assessments.questioncategory'),
        ),
        migrations.AlterField(
            model_name='assessmentrule',
            name='question_count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['department'], name='assessments_departm_0902f4_idx'),
        ),
    ]
