# Generated by Django 5.2.16 on 2026-08-02 19:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessment_created_by_assessment_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assessment',
            name='assessments_departm_0902f4_idx',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='department',
        ),
        migrations.AddField(
            model_name='assessment',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='assessments.questioncategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessment',
            name='passing_score',
            field=models.PositiveSmallIntegerField(default=70, help_text='حداقل درصد قبولی', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['category'], name='assessments_categor_039c3f_idx'),
        ),
    ]
