# Generated by Django 5.2.16 on 2026-08-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_remove_assessment_assessments_departm_0902f4_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assessment',
            name='assessments_categor_039c3f_idx',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='category',
        ),
    ]
