# Generated by Django 5.2.16 on 2026-08-06 13:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_remove_assessment_assessments_categor_039c3f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='نام مسیر آموزشی')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='شناسه مسیر')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('icon', models.CharField(blank=True, help_text='مثلا python یا ambulance', max_length=50, verbose_name='آیکون')),
                ('color', models.CharField(default='primary', max_length=20, verbose_name='رنگ کارت')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مسیر آموزشی',
                'verbose_name_plural': 'مسیرهای آموزشی',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='learning_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='assessments.learningpath', verbose_name='مسیر آموزشی'),
        ),
    ]
