# Generated by Django 5.2.16 on 2026-08-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_learningpath_questioncategory_learning_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningobjective',
            options={'ordering': ['category__learning_path', 'category', 'order', 'code'], 'verbose_name': 'هدف آموزشی', 'verbose_name_plural': 'اهداف آموزشی'},
        ),
        migrations.AddField(
            model_name='learningpath',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='dependent_paths', to='assessments.learningpath', verbose_name='پیش\u200cنیازهای مسیر'),
        ),
    ]
