# Generated by Django 5.2.16 on 2026-08-06 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_alter_learningobjective_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='learning_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='assessments.learningpath'),
        ),
    ]
