# Generated by Django 5.2.16 on 2026-08-06 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_assessment_learning_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='assessments.learningpath'),
        ),
    ]
