# Generated by Django 5.2.16 on 2026-08-06 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_alter_assessment_learning_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ شروع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='assessments.learningpath', verbose_name='مسیر آموزشی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مسیر آموزشی کاربر',
                'verbose_name_plural': 'مسیرهای آموزشی کاربران',
                'unique_together': {('user', 'learning_path')},
            },
        ),
    ]
