# Generated by Django 5.2.16 on 2026-08-06 20:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_userlearningpath'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد دوره')),
                ('name', models.CharField(max_length=255, verbose_name='نام دوره')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات دوره')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب نمایش')),
                ('estimated_minutes', models.PositiveIntegerField(default=60, verbose_name='زمان تقریبی یادگیری (دقیقه)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='assessments.learningpath', verbose_name='مسیر آموزشی')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='dependent_courses', to='assessments.course', verbose_name='پیش\u200cنیازهای دوره')),
            ],
            options={
                'verbose_name': 'دوره آموزشی',
                'verbose_name_plural': 'دوره\u200cهای آموزشی',
                'ordering': ['learning_path', 'order', 'name'],
                'indexes': [models.Index(fields=['learning_path'], name='assessments_learnin_8453d0_idx'), models.Index(fields=['is_active'], name='assessments_is_acti_07f223_idx')],
            },
        ),
    ]
