# Generated by Django 5.2.16 on 2026-08-06 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='assessments.course', verbose_name='دوره آموزشی'),
        ),
    ]
