# Generated by Django 5.2.16 on 2026-08-06 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0012_questioncategory_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningobjective',
            options={'ordering': ['category', 'order', 'code'], 'verbose_name': 'هدف آموزشی', 'verbose_name_plural': 'اهداف آموزشی'},
        ),
        migrations.RemoveField(
            model_name='questioncategory',
            name='learning_path',
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='assessments.course', verbose_name='دوره آموزشی'),
        ),
    ]
