# Generated by Django 5.2.16 on 2026-08-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0014_auto_20260806_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('level', 'تعیین سطح'), ('practice', 'تمرین'), ('homework', 'تکلیف'), ('final', 'پایان دوره'), ('retry', 'آزمون مجدد')], default='practice', max_length=20, verbose_name='نوع آزمون'),
        ),
    ]
