# Generated by Django 5.2.16 on 2026-08-06 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0015_alter_assessment_assessment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='assessments.course', verbose_name='دوره آموزشی'),
        ),
    ]
