# Generated by Django 5.2.16 on 2026-08-06 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0016_assessment_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='assessments.course', verbose_name='دوره آموزشی'),
        ),
    ]
