# Generated by Django 5.2.16 on 2026-08-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0017_alter_assessment_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='learning_path',
        ),
        migrations.AddField(
            model_name='assessment',
            name='objectives',
            field=models.ManyToManyField(blank=True, related_name='assessments', to='assessments.learningobjective', verbose_name='اهداف آموزشی'),
        ),
    ]
