# Generated by Django 5.2.16 on 2026-08-06 23:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0018_remove_assessment_learning_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentrule',
            name='random_selection',
            field=models.BooleanField(default=True, verbose_name='انتخاب تصادفی سوالات'),
        ),
        migrations.AlterField(
            model_name='assessmentrule',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='assessments.assessment', verbose_name='آزمون'),
        ),
        migrations.AlterField(
            model_name='assessmentrule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_rules', to='assessments.questioncategory', verbose_name='دسته سوال'),
        ),
        migrations.AlterField(
            model_name='assessmentrule',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت')], max_length=20, null=True, verbose_name='سطح سختی'),
        ),
        migrations.AlterField(
            model_name='assessmentrule',
            name='learning_objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_rules', to='assessments.learningobjective', verbose_name='هدف آموزشی'),
        ),
        migrations.AlterField(
            model_name='assessmentrule',
            name='question_count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='تعداد سوال'),
        ),
    ]
