# Generated by Django 5.2.16 on 2026-08-07 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0019_assessmentrule_random_selection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['learning_path', 'parent', 'order', 'name'], 'verbose_name': 'دوره آموزشی', 'verbose_name_plural': 'دوره\u200cهای آموزشی'},
        ),
        migrations.AddField(
            model_name='course',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='assessments.course', verbose_name='دوره والد'),
        ),
    ]
