# Generated by Django 5.2.16 on 2026-08-07 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0020_alter_course_options_course_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['learning_path', 'order', 'name'], 'verbose_name': 'دوره آموزشی', 'verbose_name_plural': 'دوره\u200cهای آموزشی'},
        ),
    ]
