# Generated by Django 5.2.16 on 2026-08-18 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0021_alter_course_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'واحد آموزشی', 'verbose_name_plural': 'واحدهای آموزشی'},
        ),
    ]
