# Generated by Django 5.2.16 on 2026-08-19 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0022_alter_questioncategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='درصد تخفیف از 0 تا 100', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='قیمت پایه دوره به تومان؛ صفر یعنی رایگان', verbose_name='قیمت دوره'),
        ),
    ]
