# Generated by Django 5.2.16 on 2026-08-19 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0023_course_discount_percent_course_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار فعال\u200cسازی'), ('active', 'فعال'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت دسترسی')),
                ('payment_status', models.CharField(choices=[('not_required', 'نیازی به پرداخت نیست'), ('unpaid', 'پرداخت نشده'), ('paid', 'پرداخت شده')], default='unpaid', max_length=20, verbose_name='وضعیت پرداخت')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ فعال\u200cسازی')),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_course_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='فعال\u200cسازی توسط')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='assessments.course', verbose_name='دوره')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام دوره',
                'verbose_name_plural': 'ثبت\u200cنام\u200cهای دوره',
                'ordering': ['-enrolled_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='unique_user_course_enrollment')],
            },
        ),
    ]
