# Generated by Django 5.2.16 on 2026-08-22 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0024_courseenrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام گروه علمی')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد گروه علمی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'گروه علمی',
                'verbose_name_plural': 'گروه\u200cهای علمی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScientificGroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('scientific_manager', 'مدیر علمی'), ('question_designer', 'طراح سؤال'), ('instructor', 'مدرس')], max_length=30, verbose_name='نقش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('scientific_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='assessments.scientificgroup', verbose_name='گروه علمی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scientific_group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'عضویت گروه علمی',
                'verbose_name_plural': 'اعضای گروه\u200cهای علمی',
                'ordering': ['scientific_group', 'user', 'role'],
                'constraints': [models.UniqueConstraint(fields=('scientific_group', 'user', 'role'), name='unique_scientific_group_user_role')],
            },
        ),
    ]
