# Generated by Django 5.2.16 on 2026-08-22 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0025_scientificgroup_scientificgroupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='scientific_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='assessments.scientificgroup', verbose_name='گروه علمی'),
        ),
    ]
