# Generated by Django 5.2.16 on 2026-08-22 21:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0026_course_scientific_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInstructorAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('main', 'مدرس اصلی'), ('assistant', 'مدرس دستیار')], default='main', max_length=20, verbose_name='نقش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تخصیص')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_instructor_assignments', to='assessments.course', verbose_name='دوره')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_instructor_assignments', to=settings.AUTH_USER_MODEL, verbose_name='مدرس')),
            ],
            options={
                'verbose_name': 'تخصیص مدرس دوره',
                'verbose_name_plural': 'تخصیص\u200cهای مدرسان دوره',
                'ordering': ['course', 'role', 'instructor'],
                'constraints': [models.UniqueConstraint(fields=('course', 'instructor', 'role'), name='unique_course_instructor_assignment')],
            },
        ),
    ]
