# Generated by Django 5.2.16 on 2026-08-24 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0027_courseinstructorassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='learning_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='assessments.learningpath', verbose_name='مسیر آموزشی'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='assessments.course', verbose_name='دوره آموزشی'),
        ),
    ]
