# Generated by Django 5.2.16 on 2026-08-24 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0029_assessmentenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='demo_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='تعداد دفعاتی که کاربر قبل از خرید می\u200cتواند آزمون را آزمایش کند.', verbose_name='تعداد تلاش آزمایشی'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='درصد تخفیف از 0 تا 100', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='قیمت پایه آزمون به تومان؛ صفر یعنی رایگان', verbose_name='قیمت آزمون'),
        ),
    ]
