# Generated by Django 5.2.16 on 2026-08-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0030_assessment_demo_attempts_assessment_discount_percent_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questioncategory',
            name='unique_category_name_per_parent',
        ),
        migrations.RemoveField(
            model_name='questioncategory',
            name='department',
        ),
        migrations.AddConstraint(
            model_name='questioncategory',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_category_name_per_parent'),
        ),
    ]
