# Generated by Django 5.2.16 on 2026-08-26 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0031_remove_questioncategory_unique_category_name_per_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='review_note',
            field=models.TextField(blank=True, verbose_name='یادداشت بررسی'),
        ),
        migrations.AddField(
            model_name='question',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی'),
        ),
        migrations.AddField(
            model_name='question',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_questions', to=settings.AUTH_USER_MODEL, verbose_name='بررسی شده توسط'),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('inactive', 'غیرفعال')], default='draft', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['status'], name='assessments_status_277ca0_idx'),
        ),
    ]
