# Generated by Django 5.2.16 on 2026-08-26 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0032_question_review_note_question_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_public',
            field=models.BooleanField(default=False, help_text='آیا همه کاربران می\u200cتوانند ثبت\u200cنام کنند؟', verbose_name='آزمون عمومی'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='scientific_group',
            field=models.ForeignKey(blank=True, help_text='برای آزمون\u200cهای مستقل از گروه علمی استفاده می\u200cشود', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='assessments.scientificgroup', verbose_name='گروه علمی'),
        ),
        migrations.AlterField(
            model_name='course',
            name='learning_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='assessments.learningpath', verbose_name='مسیر آموزشی'),
        ),
    ]
