# Generated by Django 5.2.16 on 2026-08-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0033_assessment_is_public_assessment_scientific_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='source_courses',
            field=models.ManyToManyField(blank=True, help_text='دوره\u200cهایی که سوالات آزمون از آن\u200cها انتخاب می\u200cشود', related_name='source_assessments', to='assessments.course', verbose_name='دوره\u200cهای منبع سوالات'),
        ),
    ]
