# Generated by Django 5.2.16 on 2026-08-26 19:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0034_assessment_source_courses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionReviewHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('submit', 'ارسال برای تایید'), ('approve', 'تایید'), ('reject', 'رد'), ('return', 'برگشت برای اصلاح'), ('comment', 'یادداشت')], max_length=20, verbose_name='اقدام')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='assessments.question', verbose_name='سوال')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_review_history', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تاریخچه بررسی سوال',
                'verbose_name_plural': 'تاریخچه بررسی سوالات',
                'ordering': ['created_at'],
            },
        ),
    ]
