# Generated by Django 5.2.16 on 2026-08-27 06:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0035_questionreviewhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('card', 'کارت بانکی'), ('shaba', 'شماره شبا'), ('crypto', 'کیف پول دیجیتال')], default='card', max_length=20, verbose_name='نوع حساب')),
                ('title', models.CharField(help_text='مثلاً: کارت بانک ملی', max_length=100, verbose_name='عنوان')),
                ('account_number', models.CharField(max_length=100, verbose_name='شماره حساب/کارت/آدرس کیف پول')),
                ('owner_name', models.CharField(max_length=100, verbose_name='به نام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'حساب پرداخت',
                'verbose_name_plural': 'حساب\u200cهای پرداخت',
                'ordering': ['account_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                ('tracking_code', models.CharField(blank=True, max_length=50, verbose_name='کد رهگیری')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='payment_receipts/', verbose_name='عکس رسید')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='assessments.assessment', verbose_name='آزمون')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='assessments.course', verbose_name='دوره')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'درخواست پرداخت',
                'verbose_name_plural': 'درخواست\u200cهای پرداخت',
                'ordering': ['-created_at'],
            },
        ),
    ]
