# Generated by Django 5.2.16 on 2026-08-27 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0036_paymentaccount_paymentrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('points', models.PositiveIntegerField(default=10, help_text='امتیازی که کاربر با پاسخ درست می\u200cگیرد', verbose_name='امتیاز')),
                ('feedback', models.TextField(blank=True, help_text='توضیحی که وقتی کاربر غلط جواب داد نمایش داده می\u200cشود', verbose_name='بازخورد آموزشی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='assessments.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'تمرین',
                'verbose_name_plural': 'تمرین\u200cها',
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField(default=False, verbose_name='پاسخ درست')),
                ('score_earned', models.PositiveIntegerField(default=0, verbose_name='امتیاز کسب شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.exercise', verbose_name='تمرین')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_attempts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تلاش تمرین',
                'verbose_name_plural': 'تلاش\u200cهای تمرین',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان درس')),
                ('content', models.TextField(blank=True, verbose_name='متن درس')),
                ('video', models.FileField(blank=True, null=True, upload_to='lessons/videos/', verbose_name='ویدیو')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='lessons/attachments/', verbose_name='فایل ضمیمه')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('duration_minutes', models.PositiveIntegerField(default=10, verbose_name='مدت زمان (دقیقه)')),
                ('is_free', models.BooleanField(default=False, help_text='آیا این درس برای کاربران ثبت\u200cنام نشده قابل مشاهده است؟', verbose_name='پیش\u200cنمایش رایگان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='assessments.questioncategory', verbose_name='فصل')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='assessments.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'درس\u200cها',
                'ordering': ['course', 'order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='assessments.lesson', verbose_name='درس'),
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='امتیاز کل')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'امتیاز کاربر',
                'verbose_name_plural': 'امتیازهای کاربران',
            },
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'order'], name='assessments_course__e857d5_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['is_free'], name='assessments_is_free_2e9d3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('lesson', 'question'), name='unique_lesson_question'),
        ),
    ]
