# Generated by Django 5.2.16 on 2026-08-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0037_exercise_exerciseattempt_lesson_exercise_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseattempt',
            name='exercise_type',
            field=models.CharField(choices=[('quiz', 'تستی'), ('coding', 'کدنویسی')], default='quiz', max_length=20, verbose_name='نوع تمرین'),
        ),
        migrations.AddField(
            model_name='exerciseattempt',
            name='expected_output',
            field=models.TextField(blank=True, verbose_name='خروجی مورد انتظار'),
        ),
        migrations.AddField(
            model_name='exerciseattempt',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript')], default='python', max_length=20, verbose_name='زبان برنامه\u200cنویسی'),
        ),
        migrations.AddField(
            model_name='exerciseattempt',
            name='starter_code',
            field=models.TextField(blank=True, help_text='کدی که از قبل در ادیتور هست', verbose_name='کد اولیه'),
        ),
        migrations.AddField(
            model_name='exerciseattempt',
            name='test_input',
            field=models.TextField(blank=True, verbose_name='ورودی تست'),
        ),
    ]
