# Generated by Django 5.2.16 on 2026-08-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0039_remove_exerciseattempt_exercise_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exercise',
            name='unique_lesson_question',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='question',
        ),
        migrations.AddField(
            model_name='exercise',
            name='body',
            field=models.TextField(default='', help_text='توضیح کامل تمرین برای کاربر', verbose_name='متن تمرین/سوال'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='title',
            field=models.CharField(default='تمرین', max_length=255, verbose_name='عنوان تمرین'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('coding', 'کدنویسی'), ('quiz', 'تستی')], default='coding', max_length=20, verbose_name='نوع تمرین'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['lesson', 'order'], name='assessments_lesson__b9f6a6_idx'),
        ),
    ]
