# Generated by Django 5.2.16 on 2026-08-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0040_remove_exercise_unique_lesson_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='minimum_points',
            field=models.PositiveIntegerField(default=4, help_text='کمترین امتیازی که کاربر می\u200cتواند بگیرد', verbose_name='حداقل امتیاز'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='points_deduction_per_attempt',
            field=models.PositiveIntegerField(default=2, help_text='با هر بررسی غلط، چقدر امتیاز کم شود', verbose_name='کسر امتیاز هر تلاش'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='test_cases',
            field=models.JSONField(blank=True, default=list, help_text='مثال: [{"input": "5\\n3", "expected": "8"}]', verbose_name='تست\u200cکیس\u200cها'),
        ),
    ]
