# Generated by Django 5.2.16 on 2026-08-28 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0041_exercise_minimum_points_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AddField(
            model_name='course',
            name='review_note',
            field=models.TextField(blank=True, verbose_name='یادداشت بررسی'),
        ),
        migrations.AddField(
            model_name='course',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_courses', to=settings.AUTH_USER_MODEL, verbose_name='بررسی شده توسط'),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار تایید'), ('published', 'منتشر شده'), ('rejected', 'رد شده')], default='draft', max_length=20, verbose_name='وضعیت انتشار'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='assessments_status_9eb438_idx'),
        ),
    ]
