# Generated by Django 5.2.16 on 2026-08-28 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0042_course_published_at_course_review_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificgroup',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='برای حوزه\u200cها خالی بگذارید، برای رشته\u200cها حوزه والد را انتخاب کنید', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='assessments.scientificgroup', verbose_name='گروه والد'),
        ),
        migrations.AlterField(
            model_name='scientificgroupmembership',
            name='role',
            field=models.CharField(choices=[('domain_manager', 'مدیر کل'), ('scientific_manager', 'مدیر علمی'), ('question_designer', 'طراح سوال'), ('instructor', 'مدرس')], max_length=30, verbose_name='نقش'),
        ),
    ]
