# Generated by Django 5.2.16 on 2026-08-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0043_scientificgroup_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificgroupmembership',
            name='role',
            field=models.CharField(choices=[('domain_manager', 'مدیر کل'), ('technical_manager', 'مدیر کل فنی'), ('financial_manager', 'مدیر مالی'), ('scientific_manager', 'مدیر علمی'), ('question_designer', 'طراح سوال'), ('instructor', 'مدرس')], max_length=30, verbose_name='نقش'),
        ),
    ]
