# Generated by Django 5.2.16 on 2026-08-28 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0044_alter_scientificgroupmembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncategory',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='assessments.course', verbose_name='دوره آموزشی'),
        ),
    ]
