# Generated by Django 5.2.16 on 2026-08-28 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0045_alter_questioncategory_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='scientific_group',
            field=models.ForeignKey(blank=True, help_text='حوزه\u200cای که این مسیر زیرمجموعه آن است', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_paths', to='assessments.scientificgroup', verbose_name='حوزه'),
        ),
    ]
