# Generated by Django 5.2.17 on 2026-08-29 07:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0046_learningpath_scientific_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('text', 'متن'), ('exercise', 'تمرین')], default='text', max_length=20, verbose_name='نوع محتوا')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='عنوان بخش')),
                ('text', models.TextField(blank=True, verbose_name='متن')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_contents', to='assessments.exercise', verbose_name='تمرین')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='assessments.lesson', verbose_name='درس')),
            ],
            options={
                'verbose_name': 'محتوای درس',
                'verbose_name_plural': 'محتوای درس\u200cها',
                'ordering': ['lesson', 'order'],
                'indexes': [models.Index(fields=['lesson', 'order'], name='assessments_lesson__062bad_idx')],
            },
        ),
    ]
