# Generated by Django 5.2.17 on 2026-08-29 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0047_lessoncontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='scientific_group',
            field=models.ForeignKey(blank=True, help_text='موضوعی که سوال به آن تعلق دارد', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='assessments.scientificgroup', verbose_name='موضوع'),
        ),
    ]
