# Generated by Django 5.2.17 on 2026-08-29 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0048_question_scientific_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningobjective',
            options={'ordering': ['order', 'code'], 'verbose_name': 'هدف آموزشی', 'verbose_name_plural': 'اهداف آموزشی'},
        ),
        migrations.AddField(
            model_name='learningobjective',
            name='scientific_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_objectives', to='assessments.scientificgroup', verbose_name='دوره/موضوع'),
        ),
        migrations.AlterField(
            model_name='learningobjective',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_objectives', to='assessments.questioncategory'),
        ),
        migrations.AlterField(
            model_name='question',
            name='learning_objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='assessments.learningobjective'),
        ),
    ]
