# Generated by Django 5.2.17 on 2026-08-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0049_alter_learningobjective_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificgroupmembership',
            name='role',
            field=models.CharField(choices=[('domain_manager', 'مدیر کل'), ('technical_manager', 'مدیر کل فنی'), ('financial_manager', 'مدیر مالی'), ('marketing_manager', 'مدیر تبلیغات'), ('support_manager', 'مدیر پشتیبانی'), ('scientific_manager', 'مدیر علمی'), ('question_designer', 'طراح سوال'), ('instructor', 'مدرس')], max_length=30, verbose_name='نقش'),
        ),
    ]
