# Generated by Django 5.2.17 on 2026-09-03 20:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0050_alter_scientificgroupmembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, help_text='درصد تخفیف از 0 تا 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع اعتبار')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان اعتبار')),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='تعداد کل دفعات مجاز استفاده از کد', verbose_name='حداکثر تعداد استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(blank=True, help_text='اگر خالی باشد، برای همه آزمون\u200cها قابل استفاده است', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='assessments.assessment', verbose_name='آزمون خاص')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discount_codes', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountCodeUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_percent', models.PositiveSmallIntegerField(verbose_name='درصد تخفیف اعمال شده')),
                ('original_price', models.PositiveIntegerField(verbose_name='قیمت اصلی')),
                ('discounted_price', models.PositiveIntegerField(verbose_name='قیمت پس از تخفیف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to='assessments.assessment', verbose_name='آزمون')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='assessments.discountcode', verbose_name='کد تخفیف')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_code_usages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'استفاده از کد تخفیف',
                'verbose_name_plural': 'استفاده\u200cهای کد تخفیف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['code'], name='assessments_code_a906fc_idx'),
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['is_active'], name='assessments_is_acti_6b06f0_idx'),
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['valid_until'], name='assessments_valid_u_408de1_idx'),
        ),
        migrations.AddConstraint(
            model_name='discountcodeusage',
            constraint=models.UniqueConstraint(fields=('code', 'user', 'assessment'), name='unique_discount_code_usage'),
        ),
    ]
