# Generated by Django 5.2.17 on 2026-09-03 21:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0051_discountcode_discountcodeusage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='discountcodeusage',
            name='unique_discount_code_usage',
        ),
        migrations.AddConstraint(
            model_name='discountcodeusage',
            constraint=models.UniqueConstraint(fields=('code', 'user'), name='unique_discount_code_per_user'),
        ),
    ]
