# Generated by Django 5.2.17 on 2026-09-12 03:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0052_remove_discountcodeusage_unique_discount_code_usage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='questions/%Y/%m/', verbose_name='عکس')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='نام اصلی فایل')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='حجم فایل (بایت)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_question_images', to=settings.AUTH_USER_MODEL, verbose_name='آپلود شده توسط')),
            ],
            options={
                'verbose_name': 'عکس سوال',
                'verbose_name_plural': 'عکس\u200cهای سوالات',
                'ordering': ['-created_at'],
            },
        ),
    ]
