# Generated by Django 5.2.16 on 2026-08-18 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0022_alter_questioncategory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ شروع')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instructor_assignments', to='assessments.course', verbose_name='دوره آموزشی')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_assignments', to=settings.AUTH_USER_MODEL, verbose_name='مدرس')),
                ('learning_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instructor_assignments', to='assessments.learningpath', verbose_name='مسیر آموزشی')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_assignments', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'تخصیص مدرس',
                'verbose_name_plural': 'تخصیص\u200cهای مدرس',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['student', 'is_active'], name='education_i_student_97d738_idx'), models.Index(fields=['instructor', 'is_active'], name='education_i_instruc_723231_idx'), models.Index(fields=['learning_path'], name='education_i_learnin_5448a7_idx'), models.Index(fields=['course'], name='education_i_course__4839d2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('learning_path__isnull', False), ('course__isnull', False), _connector='OR'), name='assignment_has_learning_scope')],
            },
        ),
    ]
