from django.contrib.auth import views as auth_views
from django.urls import path
from.views import (
    DashboardView,
    ProfileView,
    RegisterView,
    UserLoginView,
    LearningPathDetailView,
    CourseDetailView,
    QuestionCategoryDetailView,
    LearningObjectiveDetailView,
    InstructorDashboardView,
    InstructorStudentListView,
    InstructorStudentDetailView,
    InstructorAttemptDetailView,
    InstructorStudentAttemptsView,
    CourseEnrollView,
    AdminDashboardView,
    AdminCourseListView,
    AdminLearningPathListView,
    AdminLearningPathCreateView,
    AdminLearningPathDeleteView,
    AdminCourseCreateView,
    AdminLearningPathDetailView,
)


app_name = "accounts"

urlpatterns = [
    path(
        "login/",
        UserLoginView.as_view(),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(),
        name="logout",
    ),
   
    path("dashboard/",DashboardView.as_view(),name="dashboard",),
    path(
        "admin/dashboard/",
        AdminDashboardView.as_view(),
        name="admin-dashboard",
    ),
    path(
        "admin/learning-paths/",
        AdminLearningPathListView.as_view(),
        name="admin-learning-paths",
    ),
    path(
        "admin/courses/create/",
        AdminCourseCreateView.as_view(),
        name="admin-course-create",
    ),
    path(
        "admin/learning-paths/create/",
        AdminLearningPathCreateView.as_view(),
        name="admin-learning-path-create",
    ),
    path(
        "admin/learning-paths/<uuid:pk>/delete/",
        AdminLearningPathDeleteView.as_view(),
        name="admin-learning-path-delete",
    ),
    path(
        "dashboard/path/<uuid:pk>/",
        LearningPathDetailView.as_view(),
        name="learning-path-detail",
    ),
    path(
        "admin/learning-paths/<uuid:pk>/",
        AdminLearningPathDetailView.as_view(),
        name="admin-learning-path-detail",
    ),
    path(
        "dashboard/path/<uuid:path_pk>/course/<uuid:pk>/",
        CourseDetailView.as_view(),
        name="course-detail",
    ),
    path(
        "dashboard/path/<uuid:path_pk>/course/<uuid:course_pk>/category/<uuid:pk>/",
        QuestionCategoryDetailView.as_view(),
        name="category-detail",
    ),
    path(
        "dashboard/path/<uuid:path_pk>/course/<uuid:course_pk>/category/<uuid:category_pk>/objective/<uuid:pk>/",
        LearningObjectiveDetailView.as_view(),
        name="learning-objective-detail",
    ),
    path(
        "instructor/dashboard/",
        InstructorDashboardView.as_view(),
        name="instructor-dashboard",
    ),
    path(
        "instructor/students/",
        InstructorStudentListView.as_view(),
        name="instructor-students",
    ),
    path(
        "instructor/students/<int:pk>/",
        InstructorStudentDetailView.as_view(),
        name="instructor-student-detail",
    ),
    path(
        "instructor/students/<int:pk>/attempts/",
        InstructorStudentAttemptsView.as_view(),
        name="instructor-student-attempts",
    ),
    path(
        "instructor/attempt/<uuid:pk>/",
        InstructorAttemptDetailView.as_view(),
        name="instructor-attempt-detail",
    ),
    path(
        "course/<uuid:pk>/enroll/",
        CourseEnrollView.as_view(),
        name="course-enroll",
    ),
    path(
        "admin/courses/",
        AdminCourseListView.as_view(),
        name="admin-courses",
    ),
    
    path("register/",RegisterView.as_view(),name="register",),
    path("profile/",ProfileView.as_view(),name='profile',),
]